FROM node:20-slim

WORKDIR /app

RUN apt-get update && apt-get install -y sqlite3 && rm -rf /var/lib/apt/lists/*

COPY package*.json tsconfig.json ./

RUN npm install

RUN npm install @fastify/multipart

COPY . .

CMD ["npx", "tsx", "src/index.ts"]